
version: '3.9'
services:
  konomitv:
    image: konomitv
    container_name: KonomiTV
    build:
      context: .
    # OS 起動時にコンテナを自動起動
    restart: always
    # ネットワークをホスト側と共有する
    # 標準の bridge モード (仮想ネットワーク) だと、ローカルホストとの通信が面倒
    # ref: https://inocop.hatenablog.com/entry/2018/12/18/131526
    network_mode: host
    # ボリュームのマウント設定
    # /host-rootfs/ はコンテナ内の KonomiTV からホストマシンのファイルを読み書きするために必要
    volumes:
      - type: bind
        source: './config.yaml'
        target: '/code/config.yaml'
      - type: bind
        source: './server/data/'
        target: '/code/server/data/'
      - type: bind
        source: './server/logs/'
        target: '/code/server/logs/'
      - type: bind
        source: '/'
        target: '/host-rootfs/'

    # ==================== ↓↓↓↓↓ ここからユーザー設定 ↓↓↓↓↓ ====================

    # QSVEncC / VCEEncC を利用する (Intel Graphics / AMD GPU にアクセスする) ために必要な設定
    # VCEEncC (AMD GPU) を利用するには、別途 AMDGPU-PRO Driver のインストールが必要です。
    # GPU が1個も搭載されていない (/dev/dri/ 以下のデバイスファイルが存在しない) 特殊な環境では、
    # コメントアウトしてこの設定を無効にしないと、KonomiTV サーバーを起動できなくなります。
    devices:
      - '/dev/dri/:/dev/dri/'

    # NVEncC を利用する (NVIDIA GPU にアクセスする) ために必要な設定
    # NVEncC (NVIDIA GPU) を利用するには、別途 NVIDIA Graphics Driver と
    # NVIDIA Container Toolkit のインストールが必要です。
    # コメントアウトを解除してこの設定を有効にすると、NVIDIA GPU が搭載されていない環境では KonomiTV サーバーを起動できなくなります。
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [compute, utility, video]

    # ==================== ↑↑↑↑↑ ここまでユーザー設定 ↑↑↑↑↑ ====================
