[tool.poetry]
name = "KonomiTV"
version = "0.10.1"
description = "KonomiTV: Kept Organized, Notably Optimized, Modern Interface TV media server"
package-mode = false

[tool.taskipy.tasks]
serve = "python KonomiTV.py"
dev = "python KonomiTV.py --reload"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
aerich = "^0.7.2"
aiofiles = "^23.2.1"
aiohttp = "^3.9.4"
ariblib = { url = "https://github.com/tsukumijima/ariblib/releases/download/v0.1.4/ariblib-0.1.4-py3-none-any.whl" }
biim = { url = "https://github.com/tsukumijima/biim/releases/download/v1.10.2-patch2/biim-1.10.2-py3-none-any.whl" }
colorama = "^0.4.6"
elevate = "^0.1.3"
fastapi = "^0.109.1"
fastapi-restful = "^0.5.0"
hashids = "^1.3.1"
httpx = {version = "^0.25.2", extras = ["http2"]}
passlib = {version = "^1.7.4", extras = ["bcrypt"]}
pillow = "^10.3.0"
ping3 = "^4.0.4"
psutil = "^5.9.6"
puremagic = "^1.15"
py7zr = "^0.20.8"
pydantic = "^2.5.2"
pymediainfo = "^6.1.0"
python-jose = {version = "^3.3.0", extras = ["cryptography"]}
python-multipart = "^0.0.7"
pywin32 = {version = "^306", platform = "win32"}
requests = "^2.31.0"
rich = "^13.7.0"
"ruamel.yaml" = "^0.18.5"
sse-starlette = "^1.8.2"
taskipy = "^1.12.2"
tortoise-orm = "^0.20.0"
typer = "^0.9.0"
typing-extensions = "^4.8.0"
typing-inspect = "^0.9.0"
tweepy = "^4.14.0"
tweepy-authlib = "^1.5.0"
tzdata = "^2023.3"
uvicorn = {version = "^0.24.0.post1", extras = ["standard"]}
uvloop = {version = "^0.19.0", platform = "linux"}
watchfiles = "^0.21.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.aerich]
tortoise_orm = "app.constants.DATABASE_CONFIG"
location = "./app/migrations/"
src_folder = "./"
